### ISSUE TITLE
[FEATURE] Update Flow Wallet username feature

### ISSUE THREAD

**Issue by JeffreyDoyle** [Outblock/FRW#69]
## Feature

Flow Wallet currently asks user's to input a username when creating a profile. This step induces user friction to the onboarding process, as users spend time thinking about which username to use, and put unnecessary emphasis on this decision.

Flow Wallet uses usernames for two purposes:

1. As an identifier other users can use when sending FT/NFT to another user
2. As the identifier for the users profile

For 1, there are existing community governed naming conventions, FlowNS and .find that Flow Wallet already supports which cover this use case. As such, we should remove Flow Wallet's naming feature and push all support toward FlowNS and .find instead.

For 2, instead of a user chosen name, Flow Wallet can instead default to numbered profiles (eg: "Profile 1" , "Profile 2" ... "Profile n") as other products Coinbase Wallet, Phantom and others choose to do. Should the user want to customize the name on their profile, they should be able to after profile creation. 

## Expected Outcomes

- [ ] Remove creating a username from the Flow Wallet onboarding userflow
- [ ] Default to naming profiles using sequential numbers (eg: "Profile 1", "Profile 2", ... "Profile n")
- [ ] Allow the user to change the name of their profile
- [ ] Remove the ability to toggle a profile as visible/invisible

## Milestones

- [ ] Designs complete
- [ ] iOS implementation complete
- [ ] Android implementation complete
- [ ] Extension implementation complete

## Platforms

- [ ] iOS
- [ ] Android
- [ ] Extension

**Comment by lmcmz** [comment]
Let's put this one on hold.
As we discussed before, i might affect following story:
1. For upcoming passkey, we might need ask user to put the name for the passkey
2. User won't able to quick identify their account in restore wallet flow, since all backup will use the same name ( Account 1 )

**Comment by JeffreyDoyle** [comment]
Per our conversation today:

- When we eventually integrate with Passkey we will add in a new workflow to prompt the user to rename their profile to something more userfriendly at the time they update to Passkey security.

Therefore, we can go ahead with this issue for no.
