### ISSUE TITLE
[FEATURE] Offload FLOW staking to 3rd party providers

### ISSUE THREAD

**Issue by JeffreyDoyle** [Outblock/FRW#70]
## Feature

Flow Wallet currently supports staking toward a node operator directly within the app.

However, Flow also supports 3rd party solutions and tools which provide this functionality. These tools include Flow Port for protocol native staking, and [increment.fi](https://app.increment.fi/staking) and [Ankr staking](https://www.ankr.com/staking/stake/flow/) for liquid staking.

To support Flow's DeFi initiatives, pushing more volume towards Flow's liquid staking operators is valuable. These users then also benefit from the user benefits of liquid staking as opposed to protocol native staking.

Flow users who need to use protocol native staking, they can continue to use Flow Port to service their requirements.

Considering these 3rd party solutions exist, Flow Wallet should remove it's in-app staking functionality, and instead route users to these solutions to service their requirements.

### In-app Staking userflow

For Flow Wallet users who wish to stake their FLOW, they can select the "Stake" button available on the wallet homepage.

This button will open the staking userflow, which then prompts the user to choose between the available 3rd party staking provider options.

A UI must be displayed, which outlines the staking provider options, grouped as either "Protocol native" (Flow Port) or "Liquid staking" (increment.fi and ankr staking). 

For users who have previously staked with Flow Wallet, messaging must be displayed underneath the "Protocol native" grouping, instructing these users to manage their staked FLOW using these providers.

The options highlighted under "Liquid staking" should be flagged as "reccomended".

## Milestones

- [ ] Confirm users who have previously staked with Flow Wallet can manage their staked FLOW using Flow Port (@lmcmz )
- [ ] Designs complete
- [ ] iOS implementation complete
- [ ] Android implementation complete
- [ ] Extension implementation complete

## Platforms

- [ ] iOS
- [ ] Android
- [ ] Extension

**Comment by JeffreyDoyle** [comment]
Need to:

- Investigate if we can display estimated APR beside each staking provider option. 
- Ensure that the list of staking providers can grow as we onboard more to the Flow ecosystem.
- Ensure that users with FLOW on Cadence are able to easily use it with EVM staking options.
